In [1]:
#import Library NumPy
import numpy as np

**Numpy Array**

Array NumPy adalah cara utama kita akan menggunakan Numpy selama kursus. Array Numpy pada dasarnya masuk
dua rasa: vektor dan matriks. Vektor benar-benar array 1-d dan matriks 2-d (tetapi Anda harus mencatat a
matriks masih dapat memiliki hanya satu baris atau satu kolom).

**Membuat Array NumPy**

**Dari Daftar Python**

Kita dapat membuat array dengan langsung mengonversi daftar atau daftar daftar:

In [2]:
#membuat list dengan nama my_list
my_list = [1,2,3]

In [3]:
#membuat array menggunakan Numpy dengan data list my_list
np.array(my_list)

array([1, 2, 3])

In [4]:
#membuat matriks dengan nama my_matrix
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [5]:
#meng-print hasil my_matrix
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
#membuat array menggunakan NumPy dengan data matriks my_matrix
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Metode Bawaan**

Ada banyak cara bawaan untuk menghasilkan Array

**mengatur**

Mengembalikan nilai dengan jarak yang sama dalam interval tertentu.

In [7]:
#membuat fungsi arange dengan awalan 1 sampai kurang dari 5 dengan kelipatan 2
np.arange(1,5,2)

array([1, 3])

In [8]:
#membuat fungsi arange dengan awalan 1 sampai dengan 10
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
#membuat fungsi arange dengan awalan 1 samapi kurang dari 10 dengan kelipatan 0.5
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

**Fungsi zeros and ones**

membuat array zeros dan ones

In [10]:
#membuat fungsi zeros
np.zeros(3)


array([0., 0., 0.])

In [11]:
#membuat matriks 5x5 dengan fungsi zeros
np.zeros((5,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
#membuat fungsi ones
np.ones(3)

array([1., 1., 1.])

In [13]:
#membuat matriks 3x3 dengan fungsi ones
np.ones((3,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

**linspace**


Mengembalikan angka dengan jarak yang sama selama interval yang ditentukan.

In [14]:
#membuat array dengan nilai 1 sampai dengan 10 dengan jumlah 20
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

In [15]:
#membuat array dengan nilai 1 sampai dengan 100 dengan jumlah 25
np.linspace(1,100,25)

array([  1.   ,   5.125,   9.25 ,  13.375,  17.5  ,  21.625,  25.75 ,
        29.875,  34.   ,  38.125,  42.25 ,  46.375,  50.5  ,  54.625,
        58.75 ,  62.875,  67.   ,  71.125,  75.25 ,  79.375,  83.5  ,
        87.625,  91.75 ,  95.875, 100.   ])

In [16]:
#membuat array dengan nilai 1 sampai dengan 1000 dengan jumlah default 50
np.linspace(1,1000)

array([   1.        ,   21.3877551 ,   41.7755102 ,   62.16326531,
         82.55102041,  102.93877551,  123.32653061,  143.71428571,
        164.10204082,  184.48979592,  204.87755102,  225.26530612,
        245.65306122,  266.04081633,  286.42857143,  306.81632653,
        327.20408163,  347.59183673,  367.97959184,  388.36734694,
        408.75510204,  429.14285714,  449.53061224,  469.91836735,
        490.30612245,  510.69387755,  531.08163265,  551.46938776,
        571.85714286,  592.24489796,  612.63265306,  633.02040816,
        653.40816327,  673.79591837,  694.18367347,  714.57142857,
        734.95918367,  755.34693878,  775.73469388,  796.12244898,
        816.51020408,  836.89795918,  857.28571429,  877.67346939,
        898.06122449,  918.44897959,  938.83673469,  959.2244898 ,
        979.6122449 , 1000.        ])

**Fungsi Eye**

Membuat matriks identitas

In [17]:
#membuat matrik identitas 4x4 dengan fungsi eye
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

**Random**

Numpy also has lots of ways to create random number arrays:

***rand***

Create an array of the given shape and populate it with random samples from a uniform distribution over [0,
1) .


In [19]:
#membuat random nilai sebanyak 5 dengan randint (random integer) yang berarti nilai randomnya ber tipe data integer 
np.random.randint(1,10,5)

array([7, 7, 5, 6, 9])

In [20]:
#membuat random nilai sebanyak 10 dengan randint (random integer) yang berarti nilai randomnya ber tipe data integer. mulai dari 5 sampai dengan 10 
np.random.randint(5,10,10)

array([7, 8, 6, 8, 5, 5, 5, 5, 5, 7])

**randn**

Kembalikan sampel (atau sampel) dari distribusi "standar normal". Tidak seperti rand yang seragam:

In [21]:
#membuat random nilai matriks 5x5 dengan randn (random dengan tipe data float)
np.random.randn(5,5)

array([[ 1.17148437, -0.39540503,  0.44356164, -1.1539517 , -0.19939321],
       [ 0.32714208,  0.54065155,  0.60338149,  0.26479611, -0.27530733],
       [-0.16836873, -0.78405332, -1.30552788, -0.49732754, -0.87735778],
       [ 1.16364781, -0.64779049,  0.79919588, -1.65658127, -1.62027078],
       [ 2.08594587, -0.06310718,  0.30077951, -0.3915304 , -1.90172297]])

**Array Attributes and Methods**

Mari kita bahas beberapa atribut dan metode atau array yang berguna:

In [22]:
#membuat variabel X dengan fungsi arange sebanyak 10
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


**Reshape**

Mengembalikan array yang berisi data yang sama dengan bentuk baru.

In [23]:
#membuat fungsi reshape dengan nilai x yang ada di sebelumnya
x.reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

**max,min,argmax,argmin**

Ini adalah metode yang berguna untuk menemukan nilai maks atau min. Atau untuk menemukan lokasi indeks mereka menggunakan argmin atau argmax

In [24]:
#mencari nilai maksimal dari X
x.max()

9

In [25]:
#mencari nilai minimal dari X
x.min()

0

In [26]:
#membuat array random dengan fungsi randn untuk variabel Y 
y = np.random.rand(5)
y

array([0.22194228, 0.16417143, 0.40712797, 0.22235596, 0.39075343])

In [27]:
#mencari nilai maksimal dari y
y.max()

0.4071279742577465

In [28]:
#mecari index dari nilai maksimal
y.argmax()

2

In [29]:
#membuat matriks dengan fungsi random randn untuk variabel z
z = np.random.rand(3,3)
z

array([[0.35316289, 0.39262044, 0.08425454],
       [0.11933735, 0.7302718 , 0.49080656],
       [0.52500101, 0.07591267, 0.33118246]])

In [30]:
#mencari nilai maksimal untuk variabel z
z.max()

0.7302717974156764

In [31]:
#mencari index dari nilai maksimal
z.argmax()

4

In [32]:
#mencari nilai minimal
z.min()

0.07591266732453872

In [33]:
#mencari index dari nilai minimal
z.argmin()

7

In [34]:
#mencari type data dari variabel Z
z.dtype

dtype('float64')

In [35]:
#mencari type data dari variabel Y
y.dtype

dtype('float64')

In [36]:
#mencari type data dari variabel X
x.dtype

dtype('int64')

In [ ]:
#randn : desimal (+/-)
#rand : desimal (+)
#randint : bilangan bulat

In [37]:
arr = np.random.rand(5)

In [38]:
arr

array([0.39145667, 0.36573527, 0.27262109, 0.10799156, 0.30908766])

In [39]:
arr[2]

0.2726210880068939

In [40]:
arr[0:2]

array([0.39145667, 0.36573527])

In [41]:
arr[1:4]=10
arr

array([ 0.39145667, 10.        , 10.        , 10.        ,  0.30908766])

In [42]:
potongan_arr = arr[1:4]

In [43]:
potongan_arr

array([10., 10., 10.])

In [44]:
arr

array([ 0.39145667, 10.        , 10.        , 10.        ,  0.30908766])

In [45]:
potongan_arr[:]=100
potongan_arr

array([100., 100., 100.])

In [46]:
arr

array([  0.39145667, 100.        , 100.        , 100.        ,
         0.30908766])

In [47]:
potongan_arr[1:2]=50
potongan_arr

array([100.,  50., 100.])

In [48]:
arr

array([  0.39145667, 100.        ,  50.        , 100.        ,
         0.30908766])

In [49]:
matriks = np.array([[11,12,13],[21,22,23],[31,32,33]])
matriks

array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [50]:
matriks[1:3]

array([[21, 22, 23],
       [31, 32, 33]])

In [51]:
matriks[1][2]

23

In [52]:
matriks[2][1]

32

In [53]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [54]:
#boolean
x > 5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [55]:
var1 = np.array([4,5,6])

In [56]:
var2 = np.array([7,8,9])

In [57]:
var1+var2

array([11, 13, 15])

In [58]:
var3 = np.arange(10)

In [59]:
var3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [60]:
var3.reshape(2,5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [61]:
var4 = np.arange(10,20)

In [62]:
var4

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [63]:
var4.reshape(2,5)

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [64]:
var5 = var3+var4
var5

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [65]:
var5.reshape(2,5)

array([[10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])